### ISSUE TITLE
Dead Code in Memory.scala

### ISSUE THREAD

**Issue by ekiwi** [chipsalliance/treadle#121]
I have been digging around the memory code a little bit more and it seems to me that large portions of the memory compiler in `executable/Memory.scala` are never tested/used.

Essentially it seems like all memories get compiled down to a `read-latency` of `0` and a `write-latency` of `1` by the `firrtl` compiler. Also, `readwrite` ports get split into separate `read` and `write` ports. Thus it seems like the code to handle combined r/w ports as well as the pipelining code for `read` ports is never really exercised.

Might be worth removing this code, or providing an option to prevent the `firrtl` compiler form performing these lowerings.

**Comment by chick** [comment]
I agree. IIRC Memory.scala was written right about the same time there was a flurry of work done on the firrtl memory passes, I should go over it again. Jack and I had some conversations about different ways memory handling might go, I'm a little afraid to break things, but it would be nice to simplify things.
