### ISSUE TITLE
Is there some BlackBox or BlackDoor methods to fill the Mem contents?

### ISSUE THREAD

**Issue by davidmlw** [chipsalliance/treadle#183]
I suppose SyncMem or AsyncMem is a kind of treadle object, is that possible to fill these mem from treadle?

**Comment by davidmlw** [comment]
it seems to be pokeMemory

**Comment by chick** [comment]
Yes, for treadle peekMemory, will work.
There is also using the [loadMemoryFromFile annotation](https://www.chisel-lang.org/api/latest/chisel3/util/experimental/loadMemoryFromFile$.html), which should work with all the backends

**Comment by chick** [comment]
@davidmlw Please take a look (and review if you have time) PR #220 which implements the new
firrtl load memory annotations
