### ISSUE TITLE
Is there an option to initialize all the register with random number?

### ISSUE THREAD

**Issue by davidmlw** [chipsalliance/treadle#202]
For the register without Init values, the firrtl spec is to initialize them with random number like real circuits. Current treadle seems to initialize all registers with zeros, it this true? Is there an option to initialize all the register with random number?

**Comment by chick** [comment]
@davidmlw not currently but I think this would be very easy to implement in treadle. Is there any particular strategy, I could put a random (correctly sized) value in every symbols, or could constrain the randomizing to just registers or other specific kinds of symbols. Perhaps there would be some separate rules for memories

**Comment by chick** [comment]
@davidmlw Please take a look at PR #215 which attempts to do this kind of randomization. It would be great if you could do a quick review

**Comment by chick** [comment]
Closing because I think #215 addresses this
