### ISSUE TITLE
How to peek and poke an internal signal or memory?

### ISSUE THREAD

**Issue by davidmlw** [chipsalliance/treadle#204]
I searched and didn't find an example.

```
peek("instA.instB.data", 42)
poke("instA.instB.data")
// or 
peek("instA_instB_data", 42)
poke("instA_instB_data")
```

**Comment by davidmlw** [comment]
I saw an example here https://github.com/freechipsproject/treadle/blob/bb72c8c34a1ff707720956c21715d3c202c7bec4/src/test/scala/treadle/MemoryUsageSpec.scala#L420-L429, using `LoadMemoryAnnotation`, which uses `ComponentName`.

While I didn't find an example for `ComponentName` to reference a deep component.

**Comment by sequencer** [comment]
try `ReferenceTarget`, I think `ComponentName` has been deprecated?

**Comment by davidmlw** [comment]
```
peek("instA.instB.data", 42)
poke("instA.instB.data")
```
should work. I verified with a small example.

ComponentName will be transformed to ReferenceTarget.

**Comment by chick** [comment]
I think this can be closed
