### ISSUE TITLE
expectMemory should mention the index in the error Message

### ISSUE THREAD

**Issue by nrother** [chipsalliance/treadle#232]
The current message for a failed `expectMemory` is something like

> Error:expect(mem_a, 15) got 17

Source: https://github.com/freechipsproject/treadle/blob/master/src/main/scala/treadle/TreadleTester.scala#L376

It would be nice to not only mention the name of the memory ("mem_a"), but also the index that was read. For me, the current error message actually looks like 15 is the index, although it is the expected value (with 17 being the actual value).

**Comment by chick** [comment]
Good idea. On my todo list. Thanks

**Comment by chick** [comment]
@nrother hopefully addressed by #326

**Comment by chick** [comment]
I believe this to be resolved
