### ISSUE TITLE
`StopException` should contain exit code and statement name

### ISSUE THREAD

**Issue by ekiwi** [chipsalliance/treadle#334]

**Comment by chick** [comment]
@ekiwi What do you mean by statement name?

**Comment by ekiwi** [comment]
> @ekiwi What do you mean by statement name?

Starting with firrtl `1.5` `stop` statements now have a `name` attribute, similar to the new `cover` statement.
So the exception should include the full hierarchical name of the statement, e.g., `TopLevel.child0.stop0`
