### ISSUE TITLE
syntax error(s) when parsing low Firrtl

### ISSUE THREAD

**Issue by wky17** [chipsalliance/treadle#415]
when I try to parser **Accumulator** low Firrtl code through treadle, 2 syntax error(s) detected.

the low Firrtl code:
```
val accuFirrtl1: String =
      s"""
         |circuit fib :
         |  module fib :
         |    input go : UInt<1>
         |    input reset : UInt<1>
         |    input clk : Clock
         |    output out : UInt<4>
         |
         |    reg n : UInt<4>, clk with :
         |      reset => (UInt<1>("h0"), n)
         |    node _T_11 = add ( n,go )
         |    node _T_12 = tail ( _T_11 , 1 )
         |    out <= n
         |    n <= mux(reset, UInt<4>("h0"), _T_12)
         |    """.stripMargin
```

when I try to parse it using: `TreadleTestHarness(Seq(FirrtlSourceAnnotation(accuFirrtl1)))`. the error is:
![image](https://user-images.githubusercontent.com/63497196/186298827-316b2f2c-0ef1-4934-80ce-ac613fcecc04.png)

but when I rewrite **Accumulator** as:
```
val accuFirrtl: String =
      s"""
         |circuit fib :
         |  module fib :
         |    input go : UInt<1>
         |    input reset1 : UInt<1>
         |    input clk : Clock
         |    output out : UInt<4>
         |
         |    reg n : UInt<4>, clk with :
         |      reset => (UInt<1>("h0"), n)
         |    out <= n
         |    n <= mux(reset1, UInt<4>("h0"), tail(add(n, go),1))
         |    """.stripMargin
```

it's compiled successfully:
![image](https://user-images.githubusercontent.com/63497196/186298953-5a15ddf1-24bd-4951-9736-4f08334af371.png)

the only difference is that I unfold the `tail(add(n, go)` expression in the failed case, while I think it's proper expression in low Firrtl.
I wonder if treadle can parse this unfold expression.

**Comment by chick** [comment]
I believe this is caused by the firrtl parser being very sensitive to spaces in some contexts.
by fixing up the use of spaces on the lines defining `_T_11` and `_T_12` the following string worked for me:
```
s"""
       |circuit fib :
       |  module fib :
       |    input go : UInt<1>
       |    input reset : UInt<1>
       |    input clk : Clock
       |    output out : UInt<4>
       |
       |    reg n : UInt<4>, clk with :
       |      reset => (UInt<1>("h0"), n)
       |    node _T_11 = add(n, go)
       |    node _T_12 = tail(_T_11 , 1)
       |    out <= n
       |    n <= mux(reset, UInt<4>("h0"), _T_12)
       |    """.stripMargin
```

**Comment by wky17** [comment]
yes this worked, thank u so much!
